= Dateibeschreibung

Bei der Bewirtschaftung eines Themas gibt es Attribute, deren Werte nicht frei erfasst, sondern aus einem vorgegebenen Katalog selektiert werden müssen (z.B. Gemeindenamen aus dem Katalog der Schwyzer Gemeinden). Die Gesamtheit der Kataloge eines Themas wird als "Stammdaten" bezeichnet. Sie werden in einer eigenen Datei gehalten (`+Stammdaten.xtf+`) und bilden eine Voraussetzung für die Datenerfassung.

Änderungen am Datenmodell und/oder Änderungen an den Stammdaten führen zu Anpassungen in der Datei `+Stammdaten.xtf+`. Die nachfolgende Tabelle zeigt, welche Stammdaten bei welchem Datenmodell zu verwenden sind.

[cols="30%, 20%, 40%, 10%",options="header"]
|===
| Modell +
(Version) | gültig ab | Beschreibung | Link
| SZ_Klimaanalyse_V1 +
(2026-06-02)
| 2026-07-31
| Diese Datei enthält die erste Version der Stammdaten. Darin sind die Einträge des Katalogs "Kuehlungspotential" falsch.
| https://raw.githubusercontent.com/ch-sz-geo/A250/91b969be79ea5f5913795688dca6ede0abc84866/data/Stammdaten.xtf[*Datei*]
| SZ_Klimaanalyse_V1 +
(2026-06-02)
| 2026-08-06
| Diese Datei enthält die aktuell gültigen Stammdaten für die Datenerfassung.
| https://raw.githubusercontent.com/ch-sz-geo/A250/bc6b10d8e38e84f503d53f17a49e9602f10df128/data/Stammdaten.xtf[*Datei*]
|===
