== [todo] Modellbeschreibung

<Das Thema ist von der zuständigen Stelle zu beschreiben. Nachfolgend ist ein Vorschlag der Abteilung GI angegeben.>

Die Klimakarte umfasst drei Bereiche:

* die Analysekarte,
* die Bewertungskarte und
* die Planungshinweiskarte.

Die **Analysekarte** zeigt die Ist-Situation bezüglich der Temperatur zu zwei Zeitpunkten: 14 Uhr am Tag und 4 Uhr in der Nacht. Als Temperaturwert wird einerseits die Lufttemperatur wie auch die physiologisch äquivalenten Temperatur (engl. "physiological equivalent temperature", PET) angegeben. Letztere eigenet sich zur Bewertung des Wärmeempfindens, weshalb die PET unter anderem in der Stadt- und Regionalplanung berücksichtigt wird. Die Analysekarte ist ein Rasterdatensatz und erstreckt sich über das ganze Kantonsgebiet sowie über Teile angrenzender Kantone. Die Werte betreffen die Aussentemperatur, weshalb Flächen, auf denen Gebäude stehen, keine Werte enthalten.

Bei der Bewertungs- und der Planungshinweiskarte ist das ganze Kanontsgebiet in Flächen gleicher Nutzung unterteilt und liegt als Vektordatensatz vor. Die nachfolgende Tabelle gibt einen Überblick über die relevanten Nutzungstypen (Spalte 1 und 2), die Zuordnung zu ihrer Gruppe (Spalte 3), die Kriterien, welche für die Situation am Tag (Spalte 4) und in der Nacht (Spalte 5) betrachtet werden sowie die Zuordnung zu ihren Klassen gemäss Datenmodell (Spalte 6):

[options="header"]
|===
| Nr | Nutzungstyp | Gruppe | Beurteilungskriterium Tag | Beurteilungskriterium Nacht | zugeordnet zu
| 1
| bewohnter Siedlungsraum
| Siedlungsfläche
| Wärmebelastung
| Überwärmung
| Wirkungsraum
| 2
| unbewohnter Siedlungsraum
| Siedlungsfläche
| Wärmebelastung
| Überwärmung
| Wirkungsraum
| 3
| Verkehrsflächen und Plätze
| Verkehrsfläche
| Wärmebelastung
| Überwärmung
| Wirkungsraum
| 4
| Bahngleise
| - - -
| - - -
| - - -
| Restfläche
| 5
| Gewässer
| - - -
| - - -
| - - -
| Restfläche
| 6
| Gründflächen
| Gründflächen
| Aufenthaltsqualität
| Kühlpotential
| Ausgleichsraum
| 7
| Wald und Gehölz
| Gründflächen
| Aufenthaltsqualität
| Kühlpotential
| Ausgleichsraum
|===

In den Gebieten der Nutzungstypen 1 bis 3 hält dich der Mensch mehrheitlich auf. Sie bilden jenen Raum, auf den die klimatischen Bedingungen auf den Menschen wirken (Wirkungsraum). Die Gebieten der Nutzungstypen 6 und 7 haben einen ausgleichenden Effekt (Ausgleichsraum). Unbewertet bleiben die Gebiete der Nutzungstypen 4 und 5. Sie zählen zur Restfläche.

Die **Bewertungskarte** zeigt auf, wie hoch die Wärmebelastung im Wirkraum ist und welches Potential vom Ausgleichsraum ausgeht. Die Beurteilungen beziehen sich wiederum auf 14:00 Uhr am Tag bzw. 4 Uhr in der Nacht.

Die **Planungshinweiskarte** richtet die Betrachtung in die Zukunft und weist auf, wie hoch der Handlungsbedarf bei den Wirkräumen bzw. der Schutzbedarf bei den Ausgleichsflächen ist.

ifdef::backend-pdf[]
<<<
endif::[]
